### PR TITLE
Update http-requests.html

### PR DESCRIPTION
**Pull request by agrabeli**

### CODE REVIEW

**Comment by agrabeli** [comment]
But I would recommend replacing the HTTP request test description with the following:

This test tries to detect online censorship based on a comparison of HTTP requests over Tor and over the network of the user. 

HTTP is a protocol which transfers or exchanges data across the internet. It does so by handling a client's request to connect to a server, and a server's response to a client's request. Every time you connect to a website, your browser (the client) sends a request through the HTTP protocol to the server which is hosting that website. A server normally responds by providing direct access to the website(s) that its hosting. In some cases though, Internet Service Providers (ISP) prevent users from accessing certain websites by blocking or redirecting their intended connections. 

To detect such cases of censorship, we have developed a test which performs HTTP requests to given websites over the network of its user, and then over the Tor network. As Tor software is designed to circumvent censorship by making its user's traffic appear to come from a different part of the world, we have chosen to use the Tor network as a baseline for comparing HTTP requests to websites. If the two results match, then there is no clear sign of network interference; but if the results are different, then the website that the user is testing is likely censored. 

If one of the following is present in the results, then there is a sign of network interference:

The length of the body of the two websites (over Tor and over the user's network) differs by some percentage
The HTTP request over the user's network fails
The HTTP headers do not match

Note: False positives might occur when the Tor control connection is being discriminated by the server. This happens, for example, when a CloudFlare CAPTCHA page appears.

What do you think? It's longer than the original version, but it might clearer to first time users.

**Comment by simonv3** [comment]
I think that's definitely much more helpful.

**Comment by hellais** [comment]
I think this is good, though I am unsure which of the two should be considered.

The one in the comment of the ticket seems more up to date, but I do have some minor comments on it:

> HTTP is a protocol which transfers or exchanges data across the internet

What is the difference between transfer and exchange? I think it's technically more accurate to say that HTTP is a protocol that allow communication between a client and a server.

> A server normally responds by providing direct access

I am uncertain about the wording here since "direct access" implies that there is also "indirect access" I would say instead something like: "A server normally responds with the content of the website it is hosting"

> prevent users from accessing certain websites by blocking or redirecting their intended connections

prevent users from accessing certain websites by blocking or interfering with the connection between them and the server

**Comment by agrabeli** [comment]
@hellais thanks! I've updated the http-requests description.

**Comment by hellais** [comment]
Looking good! Merging!

**Pull request merged**
