### PR TITLE
Add websites page

### PR DESCRIPTION
**Pull request by simonv3**
# What's Changed
* Added a really basic website view
* Added two endpoints for getting blockpage information. 
* Installed a linter that removes spaces at ends of lines. 

screenshot 2016-02-19 12 34 59

### CODE REVIEW

**Comment by hellais** [comment]
This looks very good.

There is a problem though when loading the website page for sites that include query parameters. Some encoding of those should happen when looking up the website view.

**Comment by simonv3** [comment]
@hellais good catch. I had to make the route a bit more aggressive about how it caught input. Didn't know this was even something routes could do! 

https://github.com/simonv3/ooni-api/commit/820b57f49611a41e24499df9eefa86ea03549ef1#diff-48e3fe5d1a670fa5442d1b529bc58fb3R22

Also added some encodeInput calls to clean those URLs up.

**Comment by hellais** [comment]
I added a couple of commits on top of yours that add support for integrating the ASN into the measurement view and for removing the probe IP address from it.

Note: the IP address of the database has changed. You will soon receive an email with the details.

**Comment by simonv3** [comment]
Cool, thanks!

**Pull request merged**
